version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test-mfn-manager:
    docker:
      - image: cimg/openjdk:23.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn clean install
      - run:
          command: mvn site
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
        file: /home/circleci/project/mfn-nager/aggregate-report/target/site/jacoco.xml
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test-mfn-manager:
    jobs:
      - test-mfn-manager